spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
  application:
    name: auth-server
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://localhost:30432/neo_authserver
    username: postgres
    password: Dimas123

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.server.authorization: TRACE

server:
  port: 9000