spring:
  application:
    name: auth-server

  datasource:
    url: jdbc:postgresql://localhost:30432/neo_authserver
    username: postgres
    password: Dimas123

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 9000